# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: liblief
  version: 0.12.3
source:
  - fn: lief-0.12.3.tar.gz
    sha256: 762925ad2eed642a6e7ef2cc899bcd3e93a40a2ce1dd2391d9b9ecadfe6438cf
    url: https://github.com/lief-project/LIEF/archive/0.12.3.tar.gz
build:
  number: 0
  run_exports:
    - liblief >=0.12.3,<0.13.0a0
  string: h6a678d5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.18.1 h7f8727e_0
    - ca-certificates 2022.10.11 h06a4308_0
    - cmake 3.22.1 h1fce559_0
    - expat 2.4.9 h6a678d5_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.19.2 hac12032_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libcurl 7.86.0 h91b91d3_0
    - libedit 3.1.20210910 h7f8727e_0
    - libev 4.33 h7f8727e_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.46.0 hce63b2e_0
    - libssh2 1.10.0 h8f2d780_0
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h295c915_1
    - ncurses 6.3 h5eee18b_3
    - ninja 1.10.2 h06a4308_5
    - ninja-base 1.10.2 hd09550d_5
    - openssl 1.1.1s h7f8727e_0
    - pkg-config 0.29.2 h1bed415_8
    - python 3.10.8 h7a1cb2a_1
    - readline 8.2 h5eee18b_0
    - rhash 1.4.1 h3c74f83_1
    - sqlite 3.40.0 h5082296_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.8 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
    - zstd 1.5.2 ha4553b6_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
test:
  files:
    - tests
  requires:
    - cmake
    - gcc_linux-64 11.2.0.*
    - gxx_linux-64 11.2.0.*
    - ninja
  script: run_test_liblief.sh
about:
  description: 'It turns out that many projects need to parse executable formats and
    they usually re-implement

    their own parser. Moreover these parsers are usually bound to one language.

    LIEF attempts to fill this void.

    '
  dev_url: https://github.com/lief-project/LIEF
  doc_url: https://lief-project.github.io/doc/latest/
  home: https://lief-project.github.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A cross platform library to parse, modify and abstract ELF, PE and MachO
    formats.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e5fa5831-2b60-4d3a-bbe6-4cb83d3f6037
  recipe-maintainers:
    - isuruf
    - mingwandroid
    - msarahan
  remote_url: git@github.com:AnacondaRecipes/lief-feedstock.git
  sha: fc66f512d60239dd544dd471039c5acf34119308
