{% set version = "4.12.3" %}

package:
  name: beautifulsoup4-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-{{ version }}.tar.gz
  sha256: 74e3d1928edc070d21748185c46e3fb33490f22f52a3addee9aee0f4f7781051

build:
  number: 0
  skip: True  # [py<36]

outputs:
  - name: beautifulsoup4
    script: build_base.bat  # [win]
    script: build_base.sh   # [not win]
    requirements:
      host:
        - hatchling >=1.8.0
        - pip
        - python
      run:
        - python
        - soupsieve >1.2
    test:
      imports:
        - bs4
        - bs4.builder
      requires:
        - pip
        - lxml
        - html5lib
        - pytest >=6
      commands:
        - pip check
        - pytest --pyargs bs4

  - name: bs4
    build:
      noarch: generic
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('beautifulsoup4', max_pin="x.x.x") }}
    test:
      imports:
        - bs4
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: https://beautiful-soup-4.readthedocs.io/
  dev_url: https://code.launchpad.net/beautifulsoup

extra:
  recipe-maintainers:
    - jschueller
    - nehaljwani
  skip-lints:
    - missing_wheel
    - missing_python_build_tool
