# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Jan 31 23:34:19 2023
# ------------------------------------------------

package:
  name: patchelf
  version: 0.17.2
source:
  patches:
    - patches/0002-remove-broken-test-r-path.patch
  sha256: bae2ea376072e422c196218dd9bdef0548ccc08da4de9f36b4672df84ea2d8e2
  url: https://github.com/NixOS/patchelf/releases/download/0.17.2/patchelf-0.17.2.tar.bz2
build:
  binary_relocation: false
  number: '0'
  string: h6a678d5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.71 pl5340h5eee18b_0
    - automake 1.16.5 pl5340h06a4308_1
    - binutils 2.38 h1680402_1
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gdbm 1.18 hd4cb3f1_4
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.4 h6a678d5_0
    - patch 2.7.6 h7b6447c_1001
    - perl 5.34.0 h5eee18b_2
    - readline 8.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
test:
  commands:
    - bash -c '[[ "$(patchelf --version)" =~ "patchelf 0.17.2".* ]]'
about:
  description: 'PatchELF is a small utility to modify the dynamic linker and RPATH
    of ELF

    executables.

    '
  dev_url: https://github.com/NixOS/patchelf
  doc_url: https://github.com/NixOS/patchelf/blob/master/README.md
  home: https://github.com/NixOS/patchelf
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5b97d772-2fc4-4521-a778-bae1bd50aa05
  recipe-maintainers:
    - jakirkham
    - mjuric
  remote_url: git@github.com:AnacondaRecipes/patchelf-feedstock.git
  sha: 8217a72c54680a22af6e9db2d4bf951edb636af3
