# This file created by conda-build 3.27.0
# ------------------------------------------------

package:
  name: py-lief
  version: 0.12.3
source:
  - fn: lief-0.12.3.tar.gz
    sha256: 762925ad2eed642a6e7ef2cc899bcd3e93a40a2ce1dd2391d9b9ecadfe6438cf
    url: https://github.com/lief-project/LIEF/archive/0.12.3.tar.gz
build:
  ignore_run_exports:
    - python
  number: 0
  run_exports:
    - py-lief >=0.12.3,<0.13.0a0
  string: py312h6a678d5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.19.1 h5eee18b_0
    - ca-certificates 2023.08.22 h06a4308_0
    - ccache 3.7.9 hfe4627d_0
    - cmake 3.26.4 h96355d8_0
    - expat 2.5.0 h6a678d5_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.20.1 h143b758_1
    - ld_impl_linux-64 2.38 h1181459_1
    - libcurl 8.4.0 h251f7ec_0
    - libedit 3.1.20221030 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.57.0 h2d74bed_0
    - libssh2 1.10.0 hdbd6064_2
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libuv 1.44.2 h5eee18b_0
    - lz4-c 1.9.4 h6a678d5_0
    - ncurses 6.4 h6a678d5_0
    - ninja 1.10.2 h06a4308_5
    - ninja-base 1.10.2 hd09550d_5
    - openssl 3.0.11 h7f8727e_2
    - pkg-config 0.29.2 h1bed415_8
    - python 3.12.0 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - rhash 1.4.3 hdbd6064_0
    - sqlite 3.41.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
    - zstd 1.5.5 hc292b87_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.08.22 h06a4308_0
    - expat 2.5.0 h6a678d5_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - liblief 0.12.3 h6a678d5_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.11 h7f8727e_2
    - pip 23.3 py312h06a4308_0
    - pybind11 2.10.4 py312hdb19cb5_0
    - pybind11-global 2.10.4 py312hdb19cb5_0
    - python 3.12.0 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py312h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py312h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - libgcc-ng >=11.2.0
    - liblief 0.12.3 h6a678d5_0
    - libstdcxx-ng >=11.2.0
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - lief
  requires:
    - gxx_linux-64 11.2.0.*
    - pip
about:
  description: 'It turns out that many projects need to parse executable formats and
    they usually re-implement

    their own parser. Moreover these parsers are usually bound to one language.

    LIEF attempts to fill this void.

    '
  dev_url: https://github.com/lief-project/LIEF
  doc_url: https://lief-project.github.io/doc/latest/
  home: https://lief-project.github.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A cross platform library to parse, modify and abstract ELF, PE and MachO
    formats.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - mingwandroid
    - msarahan
