# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Sep  5 18:16:56 2024
# ------------------------------------------------

package:
  name: pyodbc
  version: 5.1.0
source:
  sha256: 397feee44561a6580be08cedbe986436859563f4bb378f48224655c8e987ea60
  url: https://pypi.io/packages/source/p/pyodbc/pyodbc-5.1.0.tar.gz
build:
  number: '0'
  script: /croot/pyodbc_1725560222485/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312h6a678d5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.7.2 h06a4308_0
    - expat 2.6.3 h6a678d5_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libedit 3.1.20230828 h5eee18b_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py312h06a4308_0
    - python 3.12.4 h5148396_1
    - readline 8.2 h5eee18b_0
    - setuptools 72.1.0 py312h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024a h04d1e81_0
    - unixodbc 2.3.11 h5eee18b_0
    - wheel 0.43.0 py312h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - python >=3.12,<3.13.0a0
    - unixodbc >=2.3.11,<2.4.0a0
test:
  commands:
    - pip check
    - python -c "import pyodbc; print('\n'.join(sorted(pyodbc.drivers())))"
  imports:
    - pyodbc
  requires:
    - pip
about:
  description: 'pyodbc is a Python DB API 2 module for ODBC. This project provides
    an

    up-to-date, convenient interface to ODBC using native data types like

    datetime and decimal.

    '
  dev_url: https://github.com/mkleehammer/pyodbc
  doc_url: https://mkleehammer.github.io/pyodbc/
  home: https://github.com/mkleehammer/pyodbc
  license: MIT-0
  license_family: MIT
  license_file: LICENSE.txt
  summary: DB API Module for ODBC
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 62b1b7cc-a3c9-49d3-a729-53aaac5d4eaf
  recipe-maintainers:
    - nehaljwani
  remote_url: git@github.com:AnacondaRecipes/pyodbc-feedstock.git
  sha: 44a0518fc6d0e3970a5cc79798739e5ed499505b
