# This file created by conda-build 3.28.0
# meta.yaml template originally from:
# /work/perseverance-python-buildout/aggregate/jsonschema-specifications-feedstock/recipe, last modified Fri Dec  1 21:39:00 2023
# ------------------------------------------------

package:
  name: jsonschema-specifications
  version: 2023.7.1
source:
  sha256: c91a50404e88a1f6ba40636778e2ee08f6e24c5613fe4c53ac24578a5a7f72bb
  url: https://pypi.io/packages/source/j/jsonschema-specifications/jsonschema_specifications-2023.7.1.tar.gz
build:
  number: '0'
  script: /work/perseverance-python-buildout/croot/jsonschema-specifications_1701731664072/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.08.22 h06a4308_0
    - editables 0.3 py312h06a4308_0
    - expat 2.5.0 h6a678d5_0
    - hatch-vcs 0.3.0 py312h06a4308_1
    - hatchling 1.18.0 py312h06a4308_1
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.12 h7f8727e_0
    - packaging 23.1 py312h06a4308_0
    - pathspec 0.10.3 py312h06a4308_0
    - pip 23.3.1 py312h06a4308_0
    - pluggy 1.0.0 py312h06a4308_1
    - python 3.12.0 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py312h06a4308_0
    - setuptools-scm 7.1.0 py312h06a4308_1
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - trove-classifiers 2023.10.18 py312h06a4308_0
    - typing-extensions 4.7.1 py312h06a4308_0
    - typing_extensions 4.7.1 py312h06a4308_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py312h06a4308_0
    - xz 5.4.5 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.12,<3.13.0a0
    - referencing >=0.28.0
test:
  commands:
    - pip check
    - pytest -vv --pyargs jsonschema_specifications --cov-branch --cov=jsonschema_specifications
      --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=88
  imports:
    - jsonschema_specifications
  requires:
    - pip
    - pytest
    - pytest-cov
about:
  description: 'JSON support files from the JSON Schema Specifications (metaschemas,
    vocabularies, etc.),

    packaged for runtime access from Python as a referencing-based Schema Registry.

    '
  dev_url: https://github.com/python-jsonschema/jsonschema-specifications
  doc_url: https://jsonschema-specifications.readthedocs.io
  home: https://github.com/python-jsonschema/jsonschema-specifications
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The JSON Schema meta-schemas and vocabularies, exposed as a Registry
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
