# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Sep 24 13:43:57 2024
# ------------------------------------------------

package:
  name: more-itertools
  version: 10.3.0
source:
  sha256: e5d93ef411224fbcef366a6e8ddc4c5781bc6359d43412a65dd5964e46111463
  url: https://pypi.io/packages/source/m/more-itertools/more-itertools-10.3.0.tar.gz
build:
  number: '0'
  script: /croot/more-itertools_1727185441804/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.7.2 h06a4308_0
    - expat 2.6.3 h6a678d5_0
    - flit-core 3.9.0 py312hee27c6d_1
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py312h06a4308_0
    - python 3.12.5 h5148396_1
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py312h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.44.0 py312h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - python -m unittest discover --buffer -s=tests
  imports:
    - more_itertools
  requires:
    - pip
  source_files:
    - tests
about:
  description: 'Python''s itertools library is a gem - you can compose elegant solutions
    for a variety

    of problems with the functions it provides. In more-itertools we collect additional

    building blocks, recipes, and routines for working with Python iterables.

    '
  dev_url: https://github.com/more-itertools/more-itertools
  doc_url: https://more-itertools.readthedocs.io
  home: https://github.com/more-itertools/more-itertools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: More routines for operating on iterables, beyond itertools
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8cc27ac3-752c-4abb-a83f-5ed19af58913
  recipe-maintainers:
    - dbast
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/more-itertools-feedstock.git
  sha: aa35b2d33a91b201c6e04a492705d17ed721d5e5
